ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA3rYKPKpXzC1HizHVhr5pbRMVaeJRdIhoapdWmqNWS7aAL4j03WXycMWUYsRT4hYttNVmv9vE1c5YqkW4ghhv6rNIkcfAGLGleDpRBtPnpkUHy8vtVmwKq3HkZM5hvEU5Z7S/WnIGDmg7DtWrqTl9zhb5R8jR2OycViToepktwK/vUf0H0WM4Sj4ZMdg9bFemZOYADH28nKxUkIseu3Yw3RrV2eOvIb4nXqZLZPY8iP/JWqfk9+6Fqj/6PpW3h1ZcnQi8gV7WVBwMjIMwMeeD7iR50UkHsO0WW6CeCfJXnIBei0sFiLbMDMt+4wgFOrCVA2Cp82rObQWcdrOYD0/Z4w== imported-openssh-key

rancher:
  network:
    dns:
      domain: box11.local
      nameservers:
        - 192.168.0.21
        - 192.168.0.12
        - 192.168.0.1

    user_docker:
      - docker
      - --insecure-registry
      - 10.0.0.0/8
      - -d
      - -s
      - overlay
      - -G
      - docker
      - -H
      - unix:///var/run/docker.sock
